name: Lint check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-check:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
      
      - name: Run prettier --check
        run: yarn prettier --check "{src,test}/**/*.ts"
      
      - name: Run eslint
        run: yarn eslint "{src,test}/**/*.ts"
